### ISSUE TITLE
position when remove tabs

### ISSUE THREAD

**Issue by calcerrada** [mikejacobson/angular-bootstrap-scrolling-tabs#10]
when working with remove dinamically tabs, tabs position left not adjust .

 [view in plunker ](http://plnkr.co/edit/m5tCakAZOeVcjaFw7DPv?p=preview)

**Comment by mikejacobson** [comment]
You're right! Good catch! v0.0.17 fixes the issue.

[Here's a fork of your plunk](http://plnkr.co/edit/v2MDurcPmHmYQJRpaOp0?p=preview) with the fix.
