### ISSUE TITLE
div "tab-content" is badly positioned

### ISSUE THREAD

**Issue by Shemesh** [mikejacobson/angular-bootstrap-scrolling-tabs#12]
hi,
@mikejacobson 

the div with class "tab-content" is positioned badly, this is causing some weird behavior with the inner content of tabs.
in order to see this clearly you can simple add this css:
.tab-content{
   background-color: orange;
}

you will see that this div (with orange color) top is the same as the top of the tab headers.
if you compare this with the original tabset you'll see that the top of this div is the **bottom** of the headers.

**Comment by mikejacobson** [comment]
Hi Shemesh,

v0.0.18 should fix this issue. The .tab-content just needed to clear the float. Thanks for letting me know about it.

I'm still trying to figure out a solution for your Issue #11. It's a pretty tricky one. I hope I can come up with something for you soon.

Thanks for using my little project!

Mike
