### ISSUE TITLE
Jquery Version?

### ISSUE THREAD

**Issue by cyberzilla** [mikejacobson/angular-bootstrap-scrolling-tabs#14]
whether there is a jquery version or not angular?, i have not learn angular, help me please

**Comment by mikejacobson** [comment]
I can probably make a jQuery plugin for it. I'll look into it and let you know.

**Comment by mikejacobson** [comment]
@cyberzilla sorry it took so long but I finally made a [jQuery plugin](https://github.com/mikejacobson/jquery-bootstrap-scrolling-tabs) version of the scrolling-tabs directive, if you're still interested.

**Comment by cyberzilla** [comment]
Thanks.....a lot master :+1:
