### ISSUE TITLE
Directive does not recognize Angular uib- prefix

### ISSUE THREAD

**Issue by bryfox** [mikejacobson/angular-bootstrap-scrolling-tabs#15]
When wrapping an Angular UI Tabset with the newer (0.14) `uib-` prefix — e.g. `uib-tabset` — the directive does not recognize that its wrapping an angular component.

Updating the finder to `isWrappingAngularUITabset = element.find('tabset, uib-tabset').length > 0,` seems to work for my purposes, but I'm not sure if there are other effects elsewhere.

**Comment by mikejacobson** [comment]
Your fix is good and won't have any other effects. I just committed v0.0.21 with your fix in it.

Thanks for letting me know about it, and providing the fix.
