### ISSUE TITLE
tab not visible

### ISSUE THREAD

**Issue by gieboyz** [mikejacobson/angular-bootstrap-scrolling-tabs#16]
Hi mike when i implement your library, i always get this error on my console
[ngTransclude:orphan] http://errors.angularjs.org/1.4.8/ngTransclude/orphan?p0=%3Cdiv%20class%3D%22scrtabs-tabs-movable-container%22%20ng-transclude%3D%22%22%3E

and my tab not visible. can you give me solution for this issue? thanks

**Comment by mikejacobson** [comment]
I'd need some information about how you're using it. I haven't seen that error before.

If you can put together a plunk that shows the error occurring, that would be the best. If you can't put it in a plunk, I'd at least need to see your markup and, if your tabs are data-driven, the underlying tabs data.

**Comment by gieboyz** [comment]
Hi mike i try to upload plnkr.co. but still not working, and i try it until working.
FYI i will use your library with combine ui-grid, as like a picture bellow 
![screenshot-localhost 2015-12-21 09-41-36](https://cloud.githubusercontent.com/assets/9793593/11922237/c54c4534-a7c7-11e5-8a29-d3d7eaa43e43.png)

![untitled2](https://cloud.githubusercontent.com/assets/9793593/11922270/2f2c84be-a7c8-11e5-83e0-ba7d8596e0ac.png)

so there is a tab with ui-grid in every tabs.

i hope this will help you to explain it.
