### ISSUE TITLE
Controller 'tabset', required by directive 'tab', can't be found!

### ISSUE THREAD

**Issue by andreas-gasser** [mikejacobson/angular-bootstrap-scrolling-tabs#17]
Hello Mike,
i get the following error using 'scrolling-tabs-wrapper'.

Detailed error:
Error: [$compile:ctreq] Controller 'tabset', required by directive 'tab', can't be found!

I can avoid the error by changing the following line on 'scrollingTabsWrapperDirective':

```
              isWrappingAngularUITabset = true,//element.find('tabset, uib-tabset').length > 0,
```

angularjs: 1.4.8
angular-bootstrap-scrolling-tabs: 0.0.22
angular-ui-bootstrap: 0.12.1

```
<div scrolling-tabs-wrapper>
  <tabset>
    <tab ng-repeat="layer in vm.results.layers"
      select="vm.updateSelectedLayer(layer)"
      heading="{{layer.label}}">
    </tab>
  </tabset>
</div>
```

**Comment by mikejacobson** [comment]
That's strange. That `element.find()` should evaluate to `true` if you're wrapping a tabset, which your markup shows you are.

If you can put together a plunk that reproduces the error, I'll look into it. If it's easier, you can fork my example of wrapping a `tabset`: http://plnkr.co/edit/DfixKK8QecSkV1R3QDrN

**Comment by andreas-gasser** [comment]
Hello Mike,

I forked your example: [http://plnkr.co/edit/dtecRdDw1Gj3QwkAwFJ8?p=preview](http://plnkr.co/edit/dtecRdDw1Gj3QwkAwFJ8?p=preview)

I changed the angular version to 1.4.8 and I added a div around the tab-container with a ng-if directive to simulate my situation.

**Comment by mikejacobson** [comment]
Ah, that `ng-if` is messing things up. If you use `ng-show` instead, it should work.

It'll take me some time to get it working when it's wrapped in an `ng-if` like that.

**Comment by noherczeg** [comment]
I'm having the exact same issue. Did you manage to make any progress regarding this problem? I can not use ng-show sadly.

**Comment by mikejacobson** [comment]
@noherczeg, v0.0.23 should fix this issue. Here's a fork of aagg1234's plunk showing it working: http://plnkr.co/edit/T9W0VO8btnIhviaxVOZh?p=preview

**Comment by noherczeg** [comment]
Niiice! Will try it out tomorrow. Thanks!

**Comment by andreas-gasser** [comment]
@mikejacobson, I made a first test and it seems to work!
Thank you for the fix!

**Comment by mikejacobson** [comment]
@aagg1234, you're welcome! Glad to hear it seems to be working. I hope it works beyond the first test. :) Sorry it took so long--I got sidetracked on some other things.

**Comment by noherczeg** [comment]
@mikejacobson I'll be able to check it out as well, but I got other stuff to work on as well currently. Will report results ASAP.
