### ISSUE TITLE
Tooltips in tab-heading are hidden

### ISSUE THREAD

**Issue by justin-john** [mikejacobson/angular-bootstrap-scrolling-tabs#18]
The tab-heading tooltips are being hidden when scrollable tabs are implemented. How to fix this issue?

![image](https://cloud.githubusercontent.com/assets/2345128/12231197/3e286614-b81b-11e5-8796-ce774f27631c.png)

Plunker: http://plnkr.co/edit/q4maN2Yaxz4hFVqUoyt1?p=preview

**Comment by mikejacobson** [comment]
Adding attribute `tooltip-append-to-body="true"` to the `span` with the `tooltip` directive on it should fix it.

[Here's a fork](http://plnkr.co/edit/Yd0ZbTf3P0MpnLwYWVWf?p=preview) of your plunk with it working.

**Comment by justin-john** [comment]
@mikejacobson Thank you. Does above solution work in case of adding dropdown in tab heading?
That is `dropdown-append-to-body="true"` to dropdown component in bootstrap.

Please see this [Plunk](http://plnkr.co/edit/xaUZYa6iriMnoQvTIINC?p=preview). Here dropdown in tab heading is working after removing the scrollable tabs.

**Comment by mikejacobson** [comment]
It looks like the `dropdown-append-to-body` feature was introduced in v0.13.0 of ui-bootstrap.

[Here's a fork](http://plnkr.co/edit/wpK9vVsZTkX09Fyfumx8?p=preview) of your plunk where I just bumped the ui-bootstrap version from 0.12.0 to 0.13.0, and it seems to be working.
