### ISSUE TITLE
Doesn't work if tabs are not visible on load

### ISSUE THREAD

**Issue by colindeclue** [mikejacobson/angular-bootstrap-scrolling-tabs#19]
I have a situation where it's possible for the tabs to be not visible when they're loaded. If this is the case, the arrows appear but the tabs do not once the tabs become visible.

If I add the following code into `watchForTabDomChanges()` in scrolling-tabs.js, it works:

```
          scope.$watch(function () {
              return $navTabs.is(":visible");
          }, function (newVal, oldVal) {
              if (newVal !== oldVal) {
                  initTabsAsWrapperWatchingTabs({
                      isWatchingDom: true
                  });
              }
          });
```

**Comment by mikejacobson** [comment]
Thanks for providing a solution! Glad you were able to get it to work for your situation.

Are you wrapping Angular UI tabs or plain Bootstrap tabs? And are you using `ng-hide`/`ng-show` for the `$navTabs` visibility or are you using `ng-if`?

I tried to reproduce your scenario but couldn't get a situation where the arrows appear but the tabs don't.
