### ISSUE TITLE
Looks like you have a jQuery dependency?

### ISSUE THREAD

**Issue by PaulL1** [mikejacobson/angular-bootstrap-scrolling-tabs#2]
Just included, but I'm getting an error.  Looking through the code, looks like a pretty firm JQuery dependency, is that correct?  If so, might be useful to note that on the front page, for those using angular-bootstrap they may be JQLite only.  

I wonder whether you could achieve everything you're doing with JQLite, which would suit me very well.  I totally understand if that's not something that's important to you though.

**Comment by mikejacobson** [comment]
You're right--sorry about that. I forgot that angular-bootstrap folks might only have jQLite.

I added a note on the front page about it. I looked into using just jQLite but there are just too many non-trivial pieces missing that I need, unfortunately: .on(), .width(), .outerWidth(), .offset(), .animate(), etc.

Sorry about that. Thanks for trying it out, though, and thanks for the suggestion.
