### ISSUE TITLE
It useless on mobile

### ISSUE THREAD

**Issue by creeds1** [mikejacobson/angular-bootstrap-scrolling-tabs#20]
On mobile if have more than 10 tabs I can't select from center it forward to the end and these from center is invisible!

**Comment by mikejacobson** [comment]
It works fine for me on iPhone 4 and iPad (Chrome & Safari) with 12 tabs. It would help if you tell me what device(s)/browser(s) you're using and how exactly you're using the directive (i.e., which use case). Ideally, it would be most helpful if you could put together a plunk that demonstrates the issue.
