### ISSUE TITLE
Error when use tab-pills if have many tab and use  watch-tabs

### ISSUE THREAD

**Issue by tranhuy605** [mikejacobson/angular-bootstrap-scrolling-tabs#24]
When you use tab-pills and have many tab, class scrtabs-tabs-movable-container have witdh incorrect

**Comment by mikejacobson** [comment]
Hi there,

v0.0.26 should fix this issue.

Thanks for letting me know about it--I never tested with >35 pills, but apparently beyond that number the width calculation is slightly off.
