### ISSUE TITLE
Rename controller context?

### ISSUE THREAD

**Issue by noherczeg** [mikejacobson/angular-bootstrap-scrolling-tabs#26]
Hey!

I think that naming your controller's context to "vm" could be a very unfortunate thing.

This is just a suggestion, but I'd recommend renaming it some specialized one. The reason is that in many-many guides/styleguides it is the conventional way for naming context in the concrete apps and this collides with it. Also by you doing a transclude as well breaks the scope chain so we can not get "our vm" by traversing up one level with `.$parent` and after that relying on the prototype chain :)

I applied a workaround for now, but if you would agree with me on this and would rename yours to a special one, then we would be able get my hack out.

Or I'd welcome any suggestions because my workaround for now is something like this:

```
<div ng-init="$ctrl = vm">
    <!-- this partial contains the tabs component in which we have our own components -->
    <div ng-include="'layout/v2/containers-partial.template.html'"></div>
</div>
```

**Comment by mikejacobson** [comment]
Excellent suggestion! That's a great point. I hadn't thought about that.

Fixed in v0.0.27.
