### ISSUE TITLE
Exampe for nested tabs

### ISSUE THREAD

**Issue by noherczeg** [mikejacobson/angular-bootstrap-scrolling-tabs#29]
Hey!

I thought that I found another bug, so I created a plunk where I nest tabs inside each other. Turns out there is no bug on your side, but I'd like to share the plunk so you could put it in your examples if you'd like to.

http://plnkr.co/edit/WOBpzFQNRmtVUIFF2gMj?p=preview

Cheers!

**Comment by mikejacobson** [comment]
Same as issue #30, closing as will not fix. [Bootstrap](http://getbootstrap.com/javascript/#tabs) doesn't support nested tabs.
