### ISSUE TITLE
Scroller not working for me? Please help

### ISSUE THREAD

**Issue by amarpreethora** [mikejacobson/angular-bootstrap-scrolling-tabs#3]
Hi Mike. First of all thank you very much for this awesome code. I needed exactly this kind of functionality. But I am facing some problem in implementation. Can you please help?

My HTML looks like this - 

<div id = "right-panel" class="resizable">
<div class="scrolling-tabs-container" ng-controller="MainController as main">
<div scrolling-tabs-wrapper>
    <tabset>
        <tab ng-repeat="tab in main.tabs" heading="{{tab.title}}" active="tab.active" disabled="tab.disabled">
       {{tab.content}}
        </tab>
    </tabset>
</div>

</div>
</div>
1. I am using AngularUI Bootstrap tabs.
2. My Module name is myApp and I have included the dependency of 'mj.scrollingTabs' and 'ui.bootstrap' in my module. 
3. I have included your 'MainService.js', 'scrolling-tabs.js' and 'MainController.js' in my HTML file and injected these controller and service in angular module myApp.
4. I have imported the required css files 'scrolling-tabs.css' and 'bootstrap.min.css' as well.

Now the issue is - I can see the left and right arrows but on click on those arrows, I am not able to scroll.  
on Browser console I am getting below error - 
TypeError: stc.$leftScrollArrow.add is not a function
    at ElementsHandler.p.setElementReferences (scrolling-tabs.js:231)
    at ElementsHandler.p.initElements (scrolling-tabs.js:170)
    at __initTabsAfterTimeout (scrolling-tabs.js:525)
    at angular-1.3.15.min.js:16298
    at completeOutstandingRequest (angular-1.3.15.min.js:4924)
    at angular-1.3.15.min.js:5312

I have spent too much time but I am not able to find the root cause of this issue. Can you please help me here?

I am using 'jquery-1.10.2.min.js' and 'angular-1.3.15.min.js'.

**Comment by mikejacobson** [comment]
Sorry you're having problems.

If you could put what you have in a plunk it would be easier to debug. But just based on the error you're getting ("TypeError: stc.$leftScrollArrow.add is not a function") it seems like maybe jQuery isn't available since ".add()" is coming from jQuery and is not included in jqLite.

Is jQuery definitely being loaded before scrolling-tabs.js?

**Comment by asantosdl** [comment]
I had the same issue, I just added jQuery before angular and the scrolling-tabs.min.js and worked fine as expected. BTW Thanks Mike

**Comment by mikejacobson** [comment]
Thanks, Alejandro! You make a great point--jQuery needs to be included before angular, not just before scrolling-tabs.js. I should have mentioned that.

And thanks for using my little project! I'm glad people are finding it useful.

**Comment by amarpreethora** [comment]
Thanks Alejandro and Mike. I put jquery before AngularJS and Scrolling-tabs.js and the error gone. But now I am facing a new issue.

My tabset is increasing tabset. Means I am pushing the tabs in tabset on click of an item. So on first load my tabset will be empty and as and when I click on items they will add in tabset. Once the tabset increases to a width more than the div, scroller should come up. When I am trying to run my app, I am getting below error now - 
Controller 'tabset', required by directive 'tabContentTransclude', can't be found!

However, I would request you to close the current issue now.

**Comment by mikejacobson** [comment]
Amar,

I realize it's probably too late to be useful for you, but I made some changes to handle your situation where your tabset increases on item click.

See the README for details. You need to add a `watch-tabs` attribute to the `scrolling-tabs-wrapper` directive element.

Here's a plunk showing it working:
http://plnkr.co/edit/DKoQ71IvWvJcp30N217i?p=preview 
Sorry it's taken so long--I haven't had much time to work on it and it was a fairly challenging fix. So thanks for the challenge! :)
