### ISSUE TITLE
Error while nesting tabsets inside each other

### ISSUE THREAD

**Issue by noherczeg** [mikejacobson/angular-bootstrap-scrolling-tabs#30]
Somethings not right when I nest divs containing tabs inside one another. I created a plunker issue where I couldn't reproduce the error in https://github.com/mikejacobson/angular-bootstrap-scrolling-tabs/issues/29, but in my real app it actually does produce wonky output.

What I observed was is that

```
<div class="tab-content" style="display: block;">
```

Sections get stacked below one another in the DOM when actually the tabsets are nested. So no matter how deep I nest any number of tabsets the content area always gets applied to the outer most tabsets list of `tab-content`.

I'm checking your code, because what I'm thinking is that a jQuery selection does not handle this well, and somehow it's writing to the wrong section of the DOM.

![image_sample](http://i.imgur.com/39a0Ndh.png)

**Comment by noherczeg** [comment]
Funny thing is when I switch root tabs then when I go back to the tab where the nested one poped out initially it gets loaded to the proper place.

Seems like some timing/lifecycle issue.

**Comment by mikejacobson** [comment]
Yeah, that's a tricky one. I never planned on handling nested tabs. The jQuery selector that selects the `.tab-content`, clones it, and appends the clone outside the movable container is just a descendant selector, so it'll get all `.tab-content` descendants, not just the one for that tabset instance.

 I'll look into it.

**Comment by mikejacobson** [comment]
I'm closing this as will not fix because Bootstrap specifically mentions in [their docs](http://getbootstrap.com/javascript/#tabs) that nested tabs are not supported. I tried a bunch of hacky things to get it to work but it just won't. Sorry about that.

**Comment by noherczeg** [comment]
@mikejacobson I didn't see that in the docs. Thanks for your response!
