### ISSUE TITLE
CSS selector does not work in production mode

### ISSUE THREAD

**Issue by trootski** [mikejacobson/angular-bootstrap-scrolling-tabs#32]
I am using Angular 1.4.3 in production with debug mode switched off. I have been trying to integrate this plugin but have run into the following issue.

Angular in debug mode does not include 'ng-scope' or 'ng-isolate-scope' classes in the DOM. This is an issue in scroll-tabs.js line 837:
`isWrappingAngularUITabset = isWrappingAngularUIBTabset || element.find('tabset, .scrtabs-tabs-movable-container .ng-isolate-scope > ul.nav').length > 0,`
Could line be changed to the following, or something similar:
`isWrappingAngularUITabset = isWrappingAngularUIBTabset || element.find('tabset, .scrtabs-tabs-movable-container div > ul.nav').length > 0,`

**Comment by mikejacobson** [comment]
v0.0.29 should fix this issue. Sorry about that--I hadn't considered that `ng-scope` and `ng-isolate-scope` classes are not included when debug mode is off.

I just implemented your proposed solution, which works for all scenarios that I tested. Thanks for suggesting a solution.

**Comment by raj-padalwar** [comment]
Hi Mike,

I had requested the same change with pull request. 
https://github.com/raj-padalwar/angular-bootstrap-scrolling-tabs/tree/raj-padalwar-patch-1

Thanks for the latest version v0.0.29. This works fine even though debug mode is off.
