### ISSUE TITLE
Can you use jQuery instead $?

### ISSUE THREAD

**Issue by Noxmox6** [mikejacobson/angular-bootstrap-scrolling-tabs#33]
Hi there,
i want to use your plugin in our application, but we dont have the variable $ for jQuery in use. Can you please change your code to the default "jQuery" function?

For example:
actual -> stc.$win = $(window);
changed -> stc.$win = jQuery(window);

Thanks :)

**Comment by mikejacobson** [comment]
v0.0.30 should fix this issue. Not sure why I wasn't passing in the alias all along.
