### ISSUE TITLE
The arrows appear wrongly untill the tab content is loaded

### ISSUE THREAD

**Issue by reizyr** [mikejacobson/angular-bootstrap-scrolling-tabs#35]
Hi,

I'm using the 'scrolling-tabs' directive, when loading the page the arrows appear whether they are needed or not. One appears above the tabs row and the other under the tabs. when the page finishes loading the arrows appear in there correct place only if they are needed.   
How can I solve these issues?

Thanks.

**Comment by mikejacobson** [comment]
v0.0.31 should fix this issue. The arrows are now hidden by default.

**Comment by reizyr** [comment]
This works fine, Thanks.
