### ISSUE TITLE
the windows is smaller, resizing the tab is not refreshing 

### ISSUE THREAD

**Issue by NisanurBulut** [mikejacobson/angular-bootstrap-scrolling-tabs#40]
![ekran alintisi](https://cloud.githubusercontent.com/assets/9026717/24330928/430e836c-1232-11e7-8809-e6091c05ddfd.PNG)

**Comment by mikejacobson** [comment]
Are you making sure to set your `triggerRefresh` flag _after_ giving the container enough time to resize?

Here's a plunk showing it working: http://plnkr.co/edit/IiYZSA61WBiqWRewwcS8?p=preview

Note that, in the MainController, I set `forceRefresh` after a delay so the `narrow` css class has had time to be added and the container has had time to resize before the tabs do their resizing.

You can try setting a breakpoint in the directive code (~ line 898) so you can see if the container is still full-size when the directive resizes itself. If so, you need to add a slight delay before triggering the refresh.

**Comment by mikejacobson** [comment]
(Sorry, didn't mean to close it.)

**Comment by NisanurBulut** [comment]
hi, ı used them, but it doesnt work :(

**Comment by mikejacobson** [comment]
Would you be able to put together a plunk that demonstrates the issue?
