### ISSUE TITLE
vertical scrollbar the right arrow go next row

### ISSUE THREAD

**Issue by shauvet** [mikejacobson/angular-bootstrap-scrolling-tabs#46]
If the window has vertical scrollbar the right arrow will go next row
Could this fix by some config? Or the way?

**Comment by mikejacobson** [comment]
It should work without any special config. Here's a plunk showing it working where the window has a vertical scrollbar:
http://plnkr.co/edit/jUCNlwmTjQl2cBe7Txoa?p=preview

Can you put together a plunk demonstrating the issue? Or at least provide more details on how exactly you're using the directive (jQuery version, angular version, etc.)?

**Comment by shauvet** [comment]
Thanks your quickly response, I think may be other css affect it, I've reduce 20px of the container,and seems the problem is been solved.

I've test in a demo out of my project, it looks OK,so  it prove your plugin is fine,it should be my special case.

Thanks for your help.Your plugin help me a lot.
