### ISSUE TITLE
Does not scroll when you add tab (angular ui-tab)

### ISSUE THREAD

**Issue by AnatolyPruchay** [mikejacobson/angular-bootstrap-scrolling-tabs#48]
Greetings!
In my case, when adding a tab, if it does not fit into the area, it disappears, most likely down below the scroll area. And as a result of this, scrolling does not work

html
```
<div scrolling-tabs-wrapper watch-tabs="workspaces">
<uib-tabset class="dashboard-tabs">
	<uib-tab ng-repeat="workspace in workspaces" disabled="workspace.disabled"
	         active="workspace.active"
	         ng-click="setActiveIndex(workspace)">
		<uib-tab-heading>
			<span ng-attr-contentEditable="{[{workspace.tabNameEditable}]}"
			      ng-dblclick="(workspace.id === 0)?disabled:editEnable(workspace)"
			      ng-blur="(workspace.id === 0)?disabled:editDisable(workspace)"
			      ng-model="workspace.name"
			      ng-change="(workspace.id === 0)?disabled:setName(workspace)">
				{[{workspace.name}]}
			</span>
			<div class="pull-right" style="margin-left: 5px;" ng-hide="$index === 0">
				<a class="close-btn on-white tab-delete" title="delete tab"
				   ng-click="(workspace.id === 0)?disabled:deleteTab(workspace)">
					<span class="fa fa-times"></span>
				</a>
			</div>
		</uib-tab-heading>
		<div>
		</div>
	</uib-tab>
	<uib-tab ng-click="addNewTab()">
		<tab-heading>
			<i class="fa fa-plus"></i>
		</tab-heading>
	</uib-tab>
</uib-tabset>
</div>
```

js 
```
$scope.workspaces = [{
            id: 0,
            name: 'default',
            active: true,
            tabNameEditable: false,
            disabled: false
}];
$scope.addNewTab = function () {
            var id = $scope.workspaces[$scope.workspaces.length - 1].id + 1;
            var tab = {
                id: id,
                paneId: 'tab' + id,
                name: 'tab ' + id,
                active: true,
                disabled: false,
                tabNameEditable: true,
                disabled: false
            };
            $scope.workspaces.push(tab);
            $scope.currentTab = tab;
        };
```

**Comment by AnatolyPruchay** [comment]
and both chevrons are visible constantly, even if there is only one tab.

**Comment by mikejacobson** [comment]
I created a plunk with your markup and code:
http://plnkr.co/edit/0HTYc9ShnJdwXHmdKxJc

(In the markup I fixed the double-curlies in `ng-attr-contentEditable="{[{workspace.tabNameEditable}]}"` and `{[{workspace.name}]}`, and in the code I deleted the extra `disabled: false` property in the `var tab = {...` declaration.)

But this just gets stuck in an infinite loop adding new tabs because the last tab is set up as an "add new tab" button, and the directive keeps clicking it automatically because it detects a change in the tabs array, so I'm not able to see your issue.

Can you put together a plunk that demonstrates the issue?

**Comment by AnatolyPruchay** [comment]
Found what the problem is. The problem is that one of the custom styles overwrites the original bootstrap styles. Because of this, and there was such a problem ... Sorry for concern)

**Comment by mikejacobson** [comment]
Excellent! Glad you figured it out. :thumbsup:
