### ISSUE TITLE
Calculating width of fixed container when used next to another element

### ISSUE THREAD

**Issue by MartinDM** [mikejacobson/angular-bootstrap-scrolling-tabs#52]
Great plugin, I'm Implementing it on of my projects, but am hoping you can assist with how to make an adjustment to the width applied to the `.fixed-container`...

I have a Plunker here to show the adjustment required:  
https://plnkr.co/edit/97u7V68zl4rSGcrr5Hl5?p=preview

I have added an extra element to the `scrollingTabsWrapperTemplate` template to wrap the components' top tabs,  _only_ in order to apply `40px` left padding to show a menu toggle alongside, but not affect the tab content width.

However, in doing so, the `.fixed-container` now gets too much width (40px) and the arrows wrap :(

In digging through the library I'm not able to see where to make a -40 pixel adjustment to the width of this element. I'm hoping it's only in one place, but unsure how many places it gets applied....

I know it's been a while since you may have worked on this, Mike, but might you know how best to minus a fixed amount from the calculated width so they don't wrap (see example ^)

Thanks for any pointers!

**Comment by mikejacobson** [comment]
The fixed-container width is essentially just set to the width of `.scrtabs-tab-wrapper-container`, the topmost element in the wrapper template. (The method doing the setting is called `setFixedContainerWidth`.) So if you can decrease that element's calculated width by `40px`, it should work.

Here's a plunk where I added `40px` of left padding to `.tabs-wrapper`, the parent element of the element hosting the directive, and it looks to be working:
https://plnkr.co/edit/EzjyPq3vZiTxvTBxF5PI?p=preview

**Comment by MartinDM** [comment]
Thanks for that Mike! I see what you've done there, and without use of an additional element as in my example, but it also means the _contents_ of the tab are also left-padded when using this approach, hence only wishing to affect the tabs UI at the top with the extra element for padding. Similar to this:    

<img width="551" alt="Screenshot 2020-01-19 at 22 17 50" src="https://user-images.githubusercontent.com/7467069/72713080-47777180-3b64-11ea-893b-71ab7991ab43.png">
(ignoring overlap onto the word itself as it'd just be an icon, but there's still space created) . 

  
I guess what I'd like is to _independency_ adjust the width of the `fixed-container` element to compensate for the left padding on the parent

**Comment by MartinDM** [comment]
It seems like even adjusting the value sent to the `.width` method with:  
`stc.$fixedContainer.width(stc.fixedContainerWidth - 80);` the `fixed-container` is still sized 40px too wide? Is it being calculated elsewhere, perhaps?     

If I drop the width directly on the element by exactly 40px, it fits into place, and the arrows line up.  

So Somewhere between `stc.$fixedContainer.width()`  and `fixed-container` width being set, perhaps there's something else being added to it?

Thanks again for your attention on this one Mike :)

**Comment by mikejacobson** [comment]
If you want to programmatically adjust the fixed-container width, you'll need to update the `stc.fixedContainerWidth` property before the fixed container's width is set to that property.

So rather than doing `stc.$fixedContainer.width(stc.fixedContainerWidth - 80);`, you should insert a line like `stc.fixedContainerWidth -= 80;` before the `.width()` method is called.

Here's a plunk showing that approach:
https://plnkr.co/edit/8qlTz1qF41U3co3TBiNe?p=preview

I added line 245 in `scrolling-tabs.js`. You'd probably need to add some styling to right-align the container, but I think that gets you the width you're looking for.

**Comment by MartinDM** [comment]
Great, thanks for that. I actually wasn't too far off as I ended up adding to line 244 instead:  
`stc.fixedContainerWidth = tabsContainerRect.width - 40 || 
(tabsContainerRect.right - tabsContainerRect.left) - 40;`
Which looks to do the trick! Thanks for the pointer as I was initially applying the adjustment in the `width` method as you mention above, so moved it outside 👍

**Comment by mikejacobson** [comment]
Stupendous! Glad it's working for you now. Thanks for using my little directive! I'm happy to hear it's still being used out there in the wild. 😺
