### ISSUE TITLE
Support nav-pills

### ISSUE THREAD

**Issue by newmanw** [mikejacobson/angular-bootstrap-scrolling-tabs#7]
currently only support for nav-tabs.

**Comment by mikejacobson** [comment]
v0.0.15 provides limited support for nav-pills: pills will work with `scrolling-tabs-wrapper` now. Thanks for the suggestion! It was never intended to work with `nav-pills` (that would probably be `angular-bootstrap-scrolling-pills`), but it wasn't too difficult to expand it in this limited way.

<a href="http://plnkr.co/edit/rN00h68xVv1w2BLGvF23?p=preview" target="_blank">Here's a plunk</a>.
